os: linux

language: node_js 
node_js:
  - 14

jobs:
  include:
    - stage: build_and_test
      script:
        - echo "Current directory: $(pwd)"
        - echo "Contents of the directory: $(ls -a)"
        - git log -n 1 --format="%H"
        - git log -n 1 --format="%P"
        - git log
        - cd npm_packages_i_created/depUpgradeChecker
        - echo "Current directory: $(pwd)"
        - npm install
        - npm config set prefix .npm-global
        - npm link
        - cd ..
        - cd ..
        - echo "Current directory: $(pwd)"
  

stages:
  - name: build_and_test
    if: branch = main
