os: darwin
arch: any

language: node_js
node_js:
  - node

before_install:
  - pwd
  - cd npm_packages_i_created/depUpgradeChecker

before_script:
  - ls -l
  - npm install
  - npm link
  - cd ..
  - cd ..
  - pwd
  - npm link depupgradecheck
  - npx depupgradecheck
