os: darwin
arch: any

language: node_js
node_js:
  - "7"

before_install:
  - npm install -g npm
  - pwd
  - cd npm_packages_i_created/depUpgradeChecker

before_script:
  - ls -l
  - npm install
  - npm link
  - cd ..
  - cd ..
  - pwd
  - npm link depupgradecheck
  - npx depupgradecheck
