language: node_js
node_js:
  - 16

before_install:
  - pwd
  - git log -n 1 --format="%H"
  - git log -n 1 --format="%P"
  - npm install depupgradecheck
  - npx depupgradecheck

before_script:
  - ls -l
  - npm install
