version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test: 
    executor: node/default 
    steps:
      - checkout

      - run:
          name: Link depUpgradeChecker in depUpgradeChecker
          command: |
 
            echo "Current directory: $(pwd)"
            echo "Contents of the directory: $(ls -a)"
            git log -n 1 --format="%H"
            git log -n 1 --format="%P"
            npm install depupgradecheck
            npx depupgradecheck


workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
