version: 2.1

jobs:
  build:
    docker:
      - image: your-docker-image
    steps:
      - checkout
      - run:
          name: Check if build should be canceled
          command: |
            if [[ "$CANCEL_BUILD" == "true" ]]; then
              echo "Build canceled based on CANCEL_BUILD environment variable"
              exit 0
            else
              echo "Continuing with the build"
            fi
      # Add other build steps here