version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test: 
    executor: node/default 
    steps:
      - checkout

      - run:
          name: Link depUpgradeChecker in depUpgradeChecker
          command: |
 
            echo "Current directory: $(pwd)"
            echo "Contents of the directory: $(ls -a)"
            git log -n 1 --format="%H"
            git log -n 1 --format="%P"
            git log
            cd npm_packages_i_created/depUpgradeChecker
            echo "Current directory: $(pwd)"
            npm install
            npm config set prefix $CIRCLE_WORKING_DIRECTORY/npm_packages_i_created/depUpgradeChecker/.npm-global
            npm link
            cd ..
            cd ..
            echo "Current directory: $(pwd)"
            npm link depupgradecheck
            npx depupgradecheck


workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
