version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Check if build should be canceled
          command: |
            if [[ "true" == "true" ]]; then
              echo "Build canceled based on CANCEL_BUILD environment variable"
              exit -1
            else
              echo "Continuing with the build"
            fi
      # Add other build steps here
# Skip CI for Dependabot PRs
if: "!startsWith(github.event.pull_request.title, 'skip ')" 