name: Check Previous Build Status

on: [push]

jobs:
  check_previous_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check Previous Build Status
        id: check_status
        uses: actions/github-script@v5
        with:
          fetch-depth: 0
          
      - name: Use the secret
        run: |
            echo "My secret: ${{ secrets.MY_SECRET }}"
            previous_commit=$(git rev-parse HEAD^1)
            status_url="https://api.github.com/repos/n66854789/tested-upgrade-n66854789/commits/${previous_commit}/statuses"
            statuses=$(curl -s $status_url)