name: Link MyPackage

on:
  push:
    branches:
      - main  # Adjust this to match your repository's default branch

jobs:
  link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: "Log"
        run: git log -n 1 --format="%H"

      # Skip CI for commits with a "skip" keyword in the commit message
      - name: Skip CI if commit message contains "skip"
        if: "contains(github.event.head_commit.message, 'Merge') != true"
        run: exit 0
      - name: Skip CI if commit message contains "bump"
        if: "contains(github.event.head_commit.message, 'Bump') != true"      
        run: exit 0
