name: CI

on:
  push:
    branches:
      - main  # Modify this to match your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Add other build steps here

# Skip CI for commits with a "skip" keyword in the commit message
if: "!contains(github.event.head_commit.message, 'skip')" 