name: Link MyPackage

on:
  push:
    branches:
      - main  # Adjust this to match your repository's default branch

jobs:
  link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install MyPackage Dependencies
        run: |
          npm install depupgradecheck

      - name: Run JavaScript script
        id: calculate_number
        run: npx depupgradecheck runremote    

      - name: Link depUpgradeChecker in depUpgradeChecker
        run: |
          cd $GITHUB_WORKSPACE
          echo "Current directory: $(pwd)"
          echo "Contents of the directory: $(ls -a)"
          git log -n 1 --format="%H"  
          git log -n 1 --format="%P" 

      - name: Use calculated number
        run: echo "The calculated number is ${{ steps.calculate_number.outputs.result }}"

          
