name: Automerge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          method: merge
